sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=master
  allow_failures:
    - env: EMACS_VERSION=master
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $CURL -O https://raw.githubusercontent.com/magnars/dash.el/master/dash.el
  - $EMACS -Q --batch -f batch-byte-compile dash.el
  - $CURL -O https://raw.githubusercontent.com/magit/with-editor/master/with-editor.el
  - $EMACS --version
script:
  - make test EMACS=$EMACS
